version: 2.1

orbs:
  gh-pages: sugarshin/gh-pages@1.0
  node: circleci/node@5.0

jobs:
  build-for-release:
    executor:
      name: node/default
      tag: "16.15"
    steps:
      - checkout
      - yarn/install-packages
      - run:
          name: Build code
          command: |
            yarn run build
      - persist_to_workspace:
          name: Pass build to next job
          root: ./dist/
          paths:
            - .
  do-release:
    executor: gh-pages/default
    steps:
      - checkout
      - attach_workspace:
          at: ./dist/
      - ghpages/deploy:
          setup-git: true
          ssh-fingerprints: "2b:9d:06:30:81:e3:3b:62:24:1c:02:a5:de:66:af:14"