version: 2.1

orbs:
  gh-pages: sugarshin/gh-pages@1.0.1
  node: circleci/node@5.0

jobs:
  build-for-release:
    executor:
      name: node/default
      tag: "16.15"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build code
          command: |
            yarn vite
      - persist_to_workspace:
          name: Pass build to next job
          root: ./dist/
          paths:
            - .
  do-release:
    executor: gh-pages/default
    steps:
      - checkout
      - attach_workspace:
          at: ./dist/
      - gh-pages/deploy:
          setup-git: true
          ssh-fingerprints: "e9:ee:e1:6d:c4:c2:6c:ff:77:99:c9:ca:f7:53:77:53"

workflows:
  Build and deploy:
    jobs:
      - build-for-release:
          name: Prepare release build
      - do-release:
          name: Deploy to Github Pages
          filters:
            branches:
              only:
                - main
                - gh-pages
          requires:
            - "Prepare release build"
