version: 2.1

orbs:
  gh-pages: sugarshin/gh-pages@1.0.1
  node: circleci/node@5.0

jobs:
  build-for-release:
    executor:
      name: node/default
      tag: "16.15"
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build code
          command: |
            yarn run build
      - persist_to_workspace:
          name: Pass build to next job
          root: ./dist/
          paths:
            - .
  do-release:
    executor: gh-pages/default
    steps:
      - checkout
      - attach_workspace:
          at: ./dist/
      - ghpages/deploy:
          setup-git: true
          ssh-fingerprints: "bc:fa:a2:63:0a:80:86:44:00:75:be:28:3c:32:0f:36"

workflows:
  Build and deploy:
    jobs:
     - build-for-release:
        name: Prep release build
        filters:
          branches:
            only: /^main$/