version: 2.1

orbs:
  gh-pages: sugarshin/gh-pages@1.0
  node: circleci/node@5.0
  slack: circleci/slack@4.10

jobs:
  build-for-release:
    executor:
      name: node/default
      tag: "16.15"
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build code
          command: |
            yarn run build
      - persist_to_workspace:
          name: Pass build to next job
          root: ./dist/
          paths:
            - .
  do-release:
    executor: gh-pages/default
    steps:
      - checkout
      - attach_workspace:
          at: ./dist/
      - gh-pages/deploy:
          setup-git: true
          ssh-fingerprints: "SHA256:QrQ6b9mnrB2xNHmxPagdk1YXR3mh/Ik55v3M3mnT/r8 npzonnenberg@gmail.com"


workflows:
  Build and deploy:
    jobs:
      - node/test:
          name: Run unit tests
          version: "16.15"
          run-command: "test:ci"
          test-results-path: "./junit.xml"
      - build-for-release:
          name: Prepare release build
          filters:
            branches:
              only: /^main$/
          requires:
            - "Run unit tests"
      - do-release:
          name: Deploy to Github Pages
          filters:
            branches:
              only: /^main$/
          context: "Slack - BmoreCodeCoffee"
          requires:
            - "Prepare release build"

