version: 2.1

orbs:
  gh-pages: sugarshin/gh-pages@1.0.1
  node: circleci/node@5.0

jobs:
  build-for-release:
    executor:
      name: node/default
      tag: "16.15"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build code
          command: |
            yarn run build
      - persist_to_workspace:
          name: Pass build to next job
          root: ./dist/
          paths:
            - .
  do-release:
    executor: gh-pages/default
    steps:
      - checkout
      - attach_workspace:
          at: ./dist/
      - gh-pages/deploy:
          setup-git: true
          ssh-fingerprints: "7f:db:90:da:0a:02:6c:3e:03:a9:9c:8c:7c:46:4c:21"

workflows:
  Build and deploy:
    jobs:
      - build-for-release:
          name: Prepare release build
          filters:
            branches:
              only: /^main$/
      - do-release:
          name: Deploy to Github Pages
          filters:
            branches:
              only: /^main$/
          requires:
            - "Prepare release build"
