import type { Metadata } from "next";
import "@/styles/index.scss";
import Hero from "@/components/Hero";

export const metadata: Metadata = {
  title: "Zonnenberg Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Hero />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
